# This workflow runs Android UI tests

name: Android Instrumented Tests

on:
  push:
    branches: [ "main" ]
    paths:
      - .github/workflows/instrumented-tests.yml
      - app/src/androidTest/**
      - app/src/main/**
      - app/build.gradle.kts
      - build-logic/*.gradle.kts
      - build-logic/src/**
      - build.gradle.kts
      - gradle/**
      - IAN/build.gradle.kts
      - IAN/*/build.gradle.kts
      - IAN/src/main/**
      - IAN/*/src/main/**
  pull_request:
    branches: [ "main" ]
    paths:
      - .github/workflows/instrumented-tests.yml
      - app/src/androidTest/**
      - app/src/main/**
      - app/build.gradle.kts
      - build-logic/**
      - build.gradle.kts
      - gradle/**
      - IAN/build.gradle.kts
      - IAN/*/build.gradle.kts
      - IAN/src/main/**
      - IAN/*/src/main/**

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        api-level: [23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36]
        orientation: [ {name: portrait, rotation: 0, skin: 480x800}, {name: landscape, rotation: 1, skin: 800x480} ]
    name: Test API ${{ matrix.api-level }} emulator (${{ matrix.orientation.name }})
    timeout-minutes: 45
    concurrency:
      group: ${{ github.workflow }}-${{ matrix.api-level }}-${{ matrix.orientation.rotation }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Generate secret files
        run: |
          echo ${{ secrets.KEYSTORE_PROPERTIES }} | base64 -d > ${{ github.workspace }}/keystore.properties
          echo ${{ secrets.GOOGLE_SERVICES }} | base64 -d > ${{ github.workspace }}/app/google-services.json

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Set up JDK 21
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          java-version-file: .tool-versions
          distribution: 'temurin'

      - name: Set up Android SDK Tools
        uses: android-actions/setup-android@651bceb6f9ca583f16b8d75b62c36ded2ae6fc9c # v4.0.0

      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v6.1.0

      - name: Run tests on API ${{ matrix.api-level }}
        uses: reactivecircus/android-emulator-runner@e89f39f1abbbd05b1113a29cf4db69e7540cae5a # v2.37.0
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.api-level >= 28 && 'playstore' || 'default' }}
          arch: x86_64
          force-avd-creation: true
          emulator-options: -no-snapshot-save -no-window -no-metrics -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none -skin ${{ matrix.orientation.skin }}
          disable-animations: true
          script: ./gradlew connectedCheck

      - name: Upload Test Results
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        if: always()
        with:
          name: "Instrumented Test Results (API ${{ matrix.api-level }}, ${{ matrix.orientation.name }})"
          path: ${{ github.workspace }}/app/build/outputs/androidTest-results/connected/**/*.xml

  publish:
    needs: test
    runs-on: ubuntu-latest
    if: always()
    permissions:
      checks: write
      pull-requests: write
    steps:
      - name: Download Test Results
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          path: tests

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/linux@c950f6fb443cb5af20a377fd0dfaa78838901040 # v2.23.0
        with:
          check_name: Instrumented Test Results
          files: tests/**/*.xml
